"""Initial migration.

Revision ID: 685ae8f0a7dc
Revises: 
Create Date: 2024-07-26 09:55:53.508437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '685ae8f0a7dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_ad', schema=None) as batch_op:
        batch_op.alter_column('passenger_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('extra_fees',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('fuel_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('door_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['id_ad'])
        batch_op.drop_column('available_date')
        batch_op.drop_column('mileage')
        batch_op.drop_column('photo')
        batch_op.drop_column('manufacture_year')
        batch_op.drop_column('provider')
        batch_op.drop_column('gps')
        batch_op.drop_column('air_conditioning')
        batch_op.drop_column('transmission')
        batch_op.drop_column('fuel_quantity')

    with op.batch_alter_table('t_advertiser', schema=None) as batch_op:
        batch_op.alter_column('id_advertiser',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('contact',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('end_hour',
               existing_type=postgresql.TIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['id_advertiser'])

    with op.batch_alter_table('t_location', schema=None) as batch_op:
        batch_op.alter_column('id_location',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['id_location'])
        batch_op.drop_column('street')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('county',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('id_location',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('t_advertiser', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('message',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('end_hour',
               existing_type=sa.Date(),
               type_=postgresql.TIME(),
               existing_nullable=True)
        batch_op.alter_column('contact',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('id_advertiser',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('t_ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transmission', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('air_conditioning', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gps', sa.CHAR(length=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('provider', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manufacture_year', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('available_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('door_number',
               existing_type=sa.String(length=45),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('fuel_type',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('extra_fees',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('passenger_number',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
